### ISSUE TITLE
Select the nearest object before OR after 

### ISSUE THREAD

**Issue by LeonB** [kana/vim-textobj-user#37]
It would be nice if I could create a textobject based on a pattern that would work line-based and would also work on text object before the cursor.

For example, I have a added an `url` textobject based on a pattern.

This works:

- This is`|` my url: http://www.google.com & this is the part after.
- `ciu`
- This is my url: `|` & this is the part after.

But this doesn't:

- This is my url: http://www.google.com & this is the part`|` after.
- `ciu`
- This is my url: http://www.google.com & this is the part`|` after.

**Comment by tommcdo** [comment]
Combining this with #44, I can imagine a spec called `'scan'` that specifics the behaviour when the cursor is not on a text object. It would have one of the following values:

`'forward-buffer'`: Scan forward for next text object in buffer (default, like current behaviour)
`'forward-line'`: Scan forward for the next text object in the line
`'backward-buffer'`: Scan backward for previous text object in the buffer
`'backward-line'`: Scan backward for previous text object in the line
`'none'` Cancel the operation

There could also be options for finding the closest text object to the cursor, but as @kana mentioned, it's hard to agree on what that means.

**Comment by kana** [comment]
It seems to be a bit confusing that "scan" implies no text object is under the cursor.  How about the following?

```
"scan"                          {string}  (default: "forward")
        A string that specifies how to find a "pattern"-based text object for
        "select".  Possible values are:

        "cursor"
                Try to find from text under the cursor.

        "forward"
                Try to find from text:
                (1) Under the cursor
                (2) After the cursor

        "nearest"
                Try to find from text:
                (1) Under the cursor
                (2) In the current line and after the cursor
                (3) In the current line and before the cursor
                (4) After the current line
                (5) Before the current line
```

**Comment by tommcdo** [comment]
These options sound very reasonable, and are much more clear that what I suggested.

I do think it would be nice to have an option that scans the current line but doesn't go beyond the current line, much like `i"`.  

One use case for this: left-hand-side and right-hand-side objects to target either side of an assignment expression. If there isn't one on the current line, it may be disorienting to jump to the next one later in the buffer.
