### ISSUE TITLE
Option to not scan for text object after cursor with 'select'

### ISSUE THREAD

**Issue by tommcdo** [kana/vim-textobj-user#44]
Vim's default text objects fail to make a selection if the cursor is not on such a text object. For example, on a line with no quotation marks, `di"` does nothing.

I would like to be able to have the same behaviour with custom text objects defined by textobj-user. Scanning could be enabled by default in order to keep the current behaviour intact, but perhaps a call like the following would cause the text object selection to fail if there isn't one under the cursor:

    call textobj#user#plugin(
    \   'pattern': '\w\+',
    \   'select': ['aw', 'iw'],
    \   'scan': 0  " Don't scan forwards for next text object
    \)

What do you think?

**Comment by kana** [comment]
That sounds a good idea.  I'll implement the option later.

**Comment by kana** [comment]
I noticed that your proposal is a variant of gh-37.  The "scan" option should not be a boolean.

**Comment by tommcdo** [comment]
Seems to work great, thank you!
