### ISSUE TITLE
Workaround to select duplicate patterns on several lines

### ISSUE THREAD

**Issue by statox** [kana/vim-textobj-user#48]
Several issues already states that vim-textobj-user doesn't handle well a text object where the begin and the end pattern are the same (see #2 and #15).

Nevertheless @kana suggested a workaround of the following form:

    call textobj#user#plugin('handyobjects', {
    \   'underscores_a': {
    \     'select': 'au',
    \     '*pattern*': '_[^_]*_'
    \   },
    \   'underscores_i': {
    \     'select': 'iu',
    \     '*pattern*': '_\zs[^_]\+\ze_'
    \   },
    \ })

I was trying to adapt this workaround to be able to search for the same pattern but on different lines, It seems that no matter how I try to add a new line in the regex it doesn't work. Can it be done or is it a limitation?

The regex I tried to use was of the following form:

    'pattern': '_[\n\|^_]*_'

An example of text to select would be

    _
    foo
    bar buzz
    _

**Comment by kana** [comment]
How about the following definitions?

```vim
call textobj#user#plugin('handyobjects', {
\   'underscores_a': {
\     'select': 'au',
\     'pattern': '_\_[^_]*_'
\   },
\   'underscores_i': {
\     'select': 'iu',
\     'pattern': '_\zs\_[^_]\+\ze_'
\   },
\ })
```

Note that these definitions do not behave the same as built-in text objects such as `ab` and `ib` in all cases.

**Comment by statox** [comment]
That is a correct workaround, thanks!

(Also your plugin is really cool!)
