### ISSUE TITLE
<SNR>52_(restore-marks) left in buffer

### ISSUE THREAD

**Issue by Asheq** [kana/vim-textobj-user#56]
Doing any `ci[textobject]` (for instance `cie` or `cil`) leaves `<SNR>52_(restore-marks)` in the buffer.

Thanks

**Comment by Asheq** [comment]
Perhaps semi-related: I'm noticing that when I specifically do a `yie`, the `'<` and `'>` marks are no longer what they should be if the last visually-selected area was character-wise (i.e. a word)

I really appreciate having this common vim-textobj-user plugin to handle edge cases like this. I know it's not easy to figure out :)

**Comment by kana** [comment]
I'll investigate the problems later.

**Comment by kana** [comment]
I've fixed the first problem.  I'll look into the second problem later.

**Comment by kana** [comment]
I've created a new issue #58 for clarity.

**Comment by Asheq** [comment]
@kana: Thanks for looking into this! I'm noticing that when using the popular [surround.vim](https://github.com/tpope/vim-surround) plugin to do `ysi[text-object]"`, it is not behaving properly anymore when the text object is one created with vim-textobj-user.

For instance, if I start with a buffer that looks like 

    hello there
    hello there

And type `ysie`, I'm oddly left in insert mode and see:

    tore-marks)ello there
    hello there

Which looks like part of `(Restore-marks)`. Any ideas?

Thanks again.

**Comment by kana** [comment]
Thank you for the report. But it's a separate problem. I'll write further progress at https://github.com/kana/vim-textobj-user/issues/59
