### ISSUE TITLE
Suggestion: Use xmap instead of vmap

### ISSUE THREAD

**Issue by Asheq** [kana/vim-textobj-user#65]
**xmap** targets just visual mode. **vmap** targets visual mode and also select mode, which I doubt that you want.

Some background on select mode: It is designed to be like selecting something in other standard editors. You select something and whatever you type immediately replaces what was selected. I believe select mode is used in snippet plugins, so I would avoid it in this plugin to avoid conflicting with those plugins.

**Comment by Asheq** [comment]
Sorry, it was actually another plugin doing this. Please ignore.

**Comment by kana** [comment]
I know. So that vim-textobj-user doesn’t define key mappings in Select mode unless {lhs} starts with non-printable characters like <C-x>.
