### ISSUE TITLE
Add doc/tags to .gitignore (based on Vim 8 documentation)

### ISSUE THREAD

**Issue by nertzy** [kana/vim-textobj-user#75]
I noticed in #32 that you rejected adding `doc/tags` to .gitignore, because you believe that people should use non-git-checkout directories as their plugins to Vim.

As of Vim 8, the [`packages-create` documentation](https://vimhelp.org/repeat.txt.html#package-create) suggests that people should be able to `git clone` vim plugin repositories directly into their package directories.

Quote:
```
This allows for the user to do: 
        mkdir ~/.vim/pack/myfoobar
        cd ~/.vim/pack/myfoobar
        git clone https://github.com/you/foobar.git
```

I believe that this justifies adding `doc/tags` to .gitignore in this project. What do you think?

Thanks for maintaining this plugin!

**Comment by kana** [comment]
Okay, I merged this: https://github.com/kana/vim-textobj-user/commit/41a675ddbeefd6a93664a4dc52f302fe3086a933
