### ISSUE TITLE
Apply command to each line in "range" / selection

### ISSUE THREAD

**Issue by amerlyq** [kana/vim-textobj-user#79]
I have a command here:
* https://github.com/amerlyq/nou.vim/blob/369c7710f782ec569d5536bc8bc43316f3f41adc/ftplugin/nou.vim#L163
```vim
nmap <buffer> <Plug>(nou-set-goal-mandatory) "_c<Plug>(textobj-nou-goal-i)!<Esc>
```
which works as `[_] task` -> `[!] task`.
Often I have multiple tasks in column and want to apply transformation in batch.
But looking through sources of textobj-user and experimenting with it had no results.
How this usecase can be implemented? 
Is it outside of scope of textobj-user or is it not solvable in general?
Am I supposed to write "range" function wrapper and apply textobj manually to each line?

**Comment by kana** [comment]
It's outside the scope of vim-textobj-user. Your usage implies modifying multiple text objects at once. But Vim can't handle multiple ranges at the same time. Therefore vim-textobj-user can't support such usage.

So you have to define a custom key mapping for that batch operation. For example:

```vim
vnoremap <buffer> <Plug>(nou-set-goal-mandatory-batch) :normal "_c<Plug>(textobj-nou-goal-i)!<C-v><Esc><CR>
```

(Note that this example assumes that `<Plug>(textobj-nou-goal-i)` selects a range within the cursor line.)

**Comment by amerlyq** [comment]
I was able to make it work only like this:
```vim
xnoremap <buffer> <Plug>(nou-set-goal-mandatory) :<C-u>exe "'<,'>norm \"_c\<Plug>(textobj-nou-goal-i)!<C-v><Esc>"<CR>
```
Ugly hell :)
