### ISSUE TITLE
Native option for blackhole register

### ISSUE THREAD

**Issue by amerlyq** [kana/vim-textobj-user#80]
Some of textobj classes aren't supposed to copy anything into registers "by design".
Suppose we have this class of command:
```vim
nmap <buffer> <Plug>(nou-set-goal-postpone) <Plug>(textobj-nou-goal-i)><Esc>
```
Workflow:
* `[_] task` exists in today's agenda
* I decided not to do it today, but want to keep entry for future -- to find out when it was planned previously
* so I copy task line `yy`, and mark task as "postponed" by above mentioned mapping
* then I move to next week agenda and past previously copied task

Problem:
* yank buffer contains previously deleted value i.e. `_` instead of whole task line

Of course, it can be solved by ad-hoc black hole register:
```vim
nmap <buffer> <Plug>(nou-set-goal-postpone) "_c<Plug>(textobj-nou-goal-i)><Esc>
```

Question:
* is using such adhoc mapping reasonable and reliable?
* is such usecase (avoiding copying) frequent in the world?
* will providing per-mapping option to textobj spec would be better for centralizing efforts?

**Comment by kana** [comment]
You usage about the blackhole register sounds reasonable.

But it's outside the scope of vim-textobj-user. Registers should be handled by operators, not text objects. And there is no way to specify the default register for a text object from that text object.

**Comment by amerlyq** [comment]
Ok, out of scope. Explicit usage likely more valid.
